### ISSUE TITLE
Reboot loop 

### ISSUE THREAD

**Issue by bhaskaranjana** [Micael106/Lenovo-Ideapad-Flex-5-14IIL05#1]
Upon trying to format the SSD of my flex 5 to APFS, it gets stuck in the midway and reboots.
I think it's a samsung ssd. Did someone else face similar problem?

**Comment by Micael106** [comment]
Any logs or pics to show?

**Comment by bhanu0002** [comment]
> Any logs or pics to show?

There is basically none. I think it has something to do with SSD. I am able to boot the online installer but it shuts down any moment while downloading the file. So now I am trying to make an offline installer from my friend's mac.
